// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTodo struct {
	Text string `json:"text"`
}

type NewUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Range struct {
	From *time.Time `json:"from"`
	To   *time.Time `json:"to"`
}

type TodoSearch struct {
	CreatedAt *Range `json:"createdAt"`
}
